export const serviceMap = {
    1: "Indoor Parking",
    2: "Outdoor Parking",
    3: "BAR",
    4: "Swimming Pool",
    5: "Lift",
    6: "Laundry Service",
    7: "Wi-Fi",
    8: "Room Service",
    9: "Gym/Fitness Center",
    10: "Spa",
    11: "Conference Room",
    12: "Banquet Hall",
    13: "Business Center",
    14: "Airport Shuttle",
    15: "Car Rental",
    16: "Bicycle Rental",
    17: "Coffee Shop",
    18: "Restaurant",
    19: "Mini Bar",
    20: "24-Hour Front Desk",
    21: "Concierge Service",
    22: "Valet Parking",
    23: "Safe Deposit Box",
    24: "Gift Shop",
    25: "Newspaper",
    26: "Garden",
    27: "Terrace",
    28: "Lounge Area",
    29: "Doctor on Call",
    30: "ATM",
    31: "Beauty Salon",
    32: "Smoking Area",
    33: "Non-Smoking Rooms",
    34: "Pet-Friendly Rooms",
    35: "Children's Playground",
    36: "Babysitting",
    37: "Laundry & Dry Cleaning",
    38: "Shoe Shine",
    39: "Meeting Rooms",
    40: "Ticket Service",
    41: "Wake-Up Service",
    42: "Ice Machine",
    43: "Private Beach",
    44: "Sauna",
    45: "Jacuzzi",
    46: "Massage Services",
    47: "Hot Tub",
    48: "Fitness Classes",
    49: "Car Parking Assistance",
    50: "Shuttle Service",
    51: "Airport Pickup",
    52: "Lift/Elevator",
    53: "Dry Cleaning",
    54: "Ironing Service",
    55: "Buffet Breakfast",
    56: "Packed Lunch",
    57: "Snack Bar",
    58: "Outdoor Furniture",
    59: "Sun Deck",
    60: "Indoor Pool",
    61: "Fitness Center/Gym",
    62: "Yoga Classes",
    63: "Aerobics Classes",
    64: "Babysitting/Child Services",
    65: "Kids Club",
    66: "Game Room",
    67: "Table Tennis",
    68: "Billiards",
    69: "Tennis Court",
    70: "Golf Course Access",
    71: "Beach Access",
    72: "Water Sports",
    73: "Medical Services",
    74: "Currency Exchange",
    75: "Safety Deposit Box",
    76: "Luggage Storage",
    77: "Newspapers",
    78: "Soundproof Rooms",
    79: "Air Conditioning",
    80: "Heating",
    81: "Fan",
    82: "Hair Dryer",
    83: "Toiletries",
    84: "Bathrobe",
    85: "Slippers",
    86: "Minibar",
    87: "Refrigerator",
    88: "Coffee/Tea Maker",
    89: "Kitchenette",
    90: "Microwave",
    91: "Dining Table",
    92: "Seating Area",
    93: "Flat Screen TV",
    94: "Cable/Satellite TV",
    95: "Telephone",
    96: "Iron",
    97: "Closet/Wardrobe",
    98: "Desk",
    99: "Balcony/Terrace",
    100: "Sound System",
    101: "Electric Kettle",
    102: "Carpeted",
    103: "Hardwood/Parquet Floors",
    104: "In-Room Safe",
    105: "Sofa",
    106: "Alarm Clock",
    107: "Laundry Basket",
    108: "Bath",
    109: "Shower",
    110: "Bathtub",
    111: "Toilet Paper",
    112: "Towels",
    113: "Bed Linen",
    114: "Pillow Menu",
    115: "Room Service (24-Hour)",
    116: "Housekeeping",
    117: "Daily Housekeeping",
    118: "Evening Housekeeping",
    119: "Extra Bedding",
    120: "Rollaway Bed",
    121: "Baby Crib",
    122: "Privacy Curtains",
    123: "Electric Socket Near Bed",
    124: "Ironing Facilities"
  };

  export const hourlyChargeTypeList = {
    halfDay4Hours40KM: "Half Day 4 Hours & 40 KM",
    fullDay8Hours80KM: "Full Day 8 Hours & 80 KM",    
  };
  
  export const outStationChargeTypeList = {
    outstationPlainArea: "Outsation Plain Area",
    outstationHillArea: "Outsation Hill Area",
  };
  
  export const extraKmChargeTypeList = {
    extraKmPlainArea: "Extra KM Plain Area",
    extraKmHillArea: "Extra KM Hill Area",
  };
  
  